#!/bin/bash
set -eu

if [[ "$DOCKERFILE_PATH" = "" ]]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

if [[ "$DOCKER_TAG" = "latest" ]]; then
    REVIEW_VERSION="3.1.0"
else
    REVIEW_VERSION="$DOCKER_TAG"
fi

docker build --build-arg REVIEW_VERSION=${REVIEW_VERSION} ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .
